### PR TITLE
add code for I2C/PCA9555 to sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c

### PR DESCRIPTION
**Pull request by dreschpe**
Add code to support I2C output board for Alex and Penelope functions.
See details at http://forum.cq-nrw.de/viewtopic.php?f=14&t=64

### CODE REVIEW

**Comment by pavel-demin** [comment]
Thanks a lot for this code!

**Comment by pavel-demin** [comment]
I've removed unneeded variables and functions from the I2C code and fixed a couple of bugs (`if(change_p = 1)` and `if(change_a = 1)`). The new version is in the develop branch:
https://github.com/pavel-demin/red-pitaya-notes/blob/develop/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c

Could you please check if it still works with your I2C board?

**Comment by dreschpe** [comment]
Hello Pavel,

the IC2 code is running.

I have a problem with the script to generate the linux system. The
compiler is missing openssl/evp.h at tools/aisimage.c.

But the bit file and the sdr-transceiver-hpsdr is compiling.

Best Regards,
Peter

Am 22.04.2016 um 02:26 schrieb Pavel Demin:

**Comment by pavel-demin** [comment]
Hello Peter,

I've again modified the I2C code. The latest version is now in the master branch:
https://github.com/pavel-demin/red-pitaya-notes/blob/master/projects/sdr_transceiver_hpsdr/server/sdr-transceiver-hpsdr.c

A new version (0.94-1058) of the Red Pitaya SDR application compatible with HPSDR is now available via the Red Pitaya application market place. I've also updated the customized SD card image.

Could you please check if this new version works with your I2C board?

I've also added some information about the I2C interface to my notes:
http://pavel-demin.github.io/red-pitaya-notes/sdr-transceiver-hpsdr/

Best Regards,

Pavel

**Pull request merged**
